- platform: template
  sensors:
    met_no_weather_temperature:
      value_template: "{{state_attr('weather.home_assistant', 'temperature')}}"
      friendly_name: "Temperatur"
      icon_template: mdi:thermometer
      unit_of_measurement: "°C"
    met_no_weather_humidity:
      value_template: "{{state_attr('weather.home_assistant', 'humidity')}}"
      friendly_name: "Luftfeuchtigkeit"
      icon_template: mdi:water-percent
      unit_of_measurement: "%"
