homeassistant:
  name: Home

  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 184
  unit_system: metric
  #temperature_unit: C
  time_zone: Europe/Moscow
  
  customize: !include_dir_merge_named includes/customize
  packages: !include_dir_merge_named includes/packages
  
  allowlist_external_dirs: 
      - /config
      - /tmp
      - /share

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

system_health:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
  
mqtt:
## Выбрать один из вариантов для брокера!  
  broker: core-mosquitto  # Локальный брокер
  ##broker: IP adress  # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant  
  username: !secret mqtt_username
  password: !secret mqtt_password
  
#lovelace_gen:

lovelace: # !include lovelace/lovelace.yaml
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module

    # Custom
    - url: /local/layout-card.js
      type: module
    - url: /local/stack-in-card.js
      type: module
    - url: /local/custom_icons.js
      type: module
    #- url: /local/vertical-stack-in-card.js?v=0.3.3
    #  type: js

    - url: 'https://fonts.googleapis.com/css?family=Raleway'
      type: css
    - url: 'https://fonts.googleapis.com/css?family=Oswald'
      type: css
    - url: 'https://fonts.googleapis.com/css?family=Quicksand'
      type: css


# Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml

# Подключение увлажнителя
fan: !include includes/fan.yaml

utility_meter: !include includes/utility_meter.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/bin_sensor
automation: !include_dir_merge_list includes/automation

# switch: !include_dir_merge_list includes/switches
# script: !include_dir_merge_named includes/scripts

# Платформа телеграмм бота - 
telegram_bot:
  - platform: polling
    api_key: !secret api_key_bot 
    allowed_chat_ids:
      - !secret telegram_id_1
  
# Платформа телеграмм уведомлений - 
notify:
  - name: telegram_id_1
    platform: telegram
    chat_id: !secret telegram_id_1

asuswrt:
  host: 192.168.1.1
  username: !secret asuswrt_login
  password: !secret asuswrt_pass 
#  protocol: telnet
  interface: eth2.2
  dnsmasq: /tmp
  sensors:
  - devices
  - upload
  - download
  - upload_speed
  - download_speed

weather:
  - platform: gismeteo
    mode: daily 

google_assistant:
  project_id: !secret google_project_id
  service_account: !include SERVICE_ACCOUNT.json
  exposed_domains:
    - switch
    - light
    - climate
    - media_player
    - sensor 
    - humidifier 
    - fan 
    - script 
