homeassistant:
  name: Home
  #  external_url: !secret main_external_url
  #  internal_url: !secret main_internal_url
  time_zone: !secret home_timezone
  unit_system: metric
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  customize: !include_dir_merge_named includes/customize
  packages: !include_dir_merge_named includes/packages

  allowlist_external_dirs:
    - /config
    - /tmp
    - /share

default_config:

system_health:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
    language: "ru"

mqtt:
  ## Выбрать один из вариантов для брокера!
  broker: core-mosquitto # Локальный брокер
  ##broker: IP adress  # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password

lovelace: !include lovelace/lovelace.yaml

lovelace_gen:

browser_mod:
  disable:
    - all

start_time:

# Платформа телеграмм бота -
telegram_bot:
  - platform: polling # or "webhooks"
    api_key: !secret telegram_bot_token
    allowed_chat_ids:
      - !secret telegram_id_dimasya1

# Платформа телеграмм уведомлений -
notify:
  - name: telegram_id_dimasya1
    platform: telegram
    chat_id: !secret telegram_id_dimasya1

weather:
  - platform: gismeteo
    mode: daily

google_assistant:
  project_id: !secret google_project_id
  service_account: !include SERVICE_ACCOUNT.json
  exposed_domains:
    - switch
    - light
    - climate
    - media_player
    - sensor
    - humidifier
    - fan
    - script

#################################################
# Inclusions
#################################################

# Вынос во внешние файлы
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml

# Подключение увлажнителя
fan: !include includes/fan.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automations
automation gui: !include automations.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list entities/sensors
binary_sensor: !include_dir_merge_list entities/binary_sensors
input_boolean: !include_dir_merge_named entities/input_boolean
timer: !include_dir_merge_named entities/timer
utility_meter: !include_dir_merge_named entities/utility_meter
