homeassistant:
  name: Home

  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 184
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Moscow
  
  customize: !include_dir_merge_named includes/customize
  packages: !include_dir_merge_named includes/packages
  
  allowlist_external_dirs: 
      - /config
      - /tmp
      - /share

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

system_health:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
  
mqtt:
## Выбрать один из вариантов для брокера!  
  broker: core-mosquitto  # Локальный брокер
  ##broker: IP adress  # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant  
  username: !secret mqtt_username
  password: !secret mqtt_password
  
lovelace: !include lovelace/lovelace.yaml

# Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/bin_sensor
automation: !include_dir_merge_list includes/automation
# switch: !include_dir_merge_list includes/switches
# script: !include_dir_merge_named includes/scripts

# Платформа телеграмм бота - 
telegram_bot:
  - platform: polling
    api_key: !secret api_key_bot 
    allowed_chat_ids:
      - !secret telegram_id_1
  
# Платформа телеграмм уведомлений - 
notify:
  - name: telegram_id_1
    platform: telegram
    chat_id: !secret telegram_id_1