- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: disk_use_percent
    arg: /
  - type: disk_free
    arg: /
  - type: last_boot

- platform: cpuspeed