- platform: template
  sensors:
    met_no_weather_temperature:
      value_template: "{{state_attr('weather.home_assistant', 'temperature')}}"
      friendly_name: "Temperatur"
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
    met_no_weather_humidity:
      value_template: "{{state_attr('weather.home_assistant', 'humidity')}}"
      friendly_name: "Luftfeuchtigkeit"
      icon_template: mdi:water-percent
      unit_of_measurement: '%'

- platform: gismeteo
  forecast: true
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - clouds
    - pressure
    - rain
    - snow
    - storm
    - geomagnetic

- platform: template
  sensors:
    gismeteo_weather_temperature:
      value_template: "{{state_attr('weather.gismeteo', 'temperature')}}"
      friendly_name: "Температура"
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
    gismeteo_weather_humidity:
      value_template: "{{state_attr('weather.gismeteo', 'humidity')}}"
      friendly_name: "Влажность"
      icon_template: mdi:water-percent
      unit_of_measurement: '%'